name: Release Module

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    uses: dnogu/ActionCI/.workflow-templates/workflows/release.yaml@main
    secrets: inherit
