name: OpenTofu

on:
  workflow_call:
    inputs:
      TF_ACTIONS_WORKING_DIR:
        required: false
        type: string
        default: "./terraform"
      OPEN_TOFU_VER:
        required: false
        type: string
        default: "latest"
      OIDC_AWS:
        required: true
        type: boolean
        default: false
      AWS_AUTH_REGION:
        required: false
        type: string
        default: "us-east-1"
      AWS_ROLE_TO_ASSUME:
        required: false
        type: string
        default: "placeholder_role"
      AWS_ROLE_SESSION_NAME:
        required: false
        type: string
        default: "MySessionName"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ inputs.TF_ACTIONS_WORKING_DIR }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      if: ${{ inputs.OIDC_AWS == true }}
      with:
        aws-region: ${{ inputs.AWS_AUTH_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-session-name: ${{ inputs.AWS_ROLE_SESSION_NAME }}

    - uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: ${{ inputs.OPEN_TOFU_VER }}

    - name: OpenTofu fmt
      id: fmt
      run: tofu fmt -check
      continue-on-error: true

    - name: OpenTofu Init
      id: init
      run: tofu init

    - name: OpenTofu Validate
      id: validate
      run: tofu validate -no-color

    - name: OpenTofu Plan
      id: plan
      run: tofu plan -no-color
      continue-on-error: true
