name: OpenTofu

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    defaults:
      run:
        working-directory: ${{ secrets.TF_ACTIONS_WORKING_DIR }}

    steps:
    - uses: actions/checkout@v3
    - uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: ${{ vars.OPEN_TOFU_VER }}

    - name: OpenTofu fmt
      id: fmt
      run: tofu fmt -check
      continue-on-error: true

    - name: OpenTofu Init
      id: init
      run: tofu init

    - name: OpenTofu Validate
      id: validate
      run: tofu validate -no-color

    - name: OpenTofu Plan
      id: plan
      run: tofu plan -no-color
      continue-on-error: true
